apiVersion: v1
kind: Service
metadata:
  name: techtrends
  labels:
    {{- include "techtrends-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if not .Values.service.targetPort}}
      targetPort: {{ .Values.service.port }}
      {{- else }}
      targetPort: {{ .Values.service.targetpPort }}
      {{- end }}
      protocol: {{ .Values.service.protocol }}
      name: http
  selector:
    {{- include "techtrends-chart.selectorLabels" . | nindent 4 }}
