apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-staging
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - value-staging.yaml
    path: nginx-deployment
    repoURL: https://github.com/zhangtreefish/python-helloworld.git
    targetRevision: HEAD
  syncPolicy: {}