apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: project/helm/techtrends-chart
    repoURL: https://github.com/zhangtreefish/nd064_course_1.git
    targetRevision: HEAD