apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: techtrends
    name: techtrends
    namespace: sandbox
  spec:
    clusterIP: 10.43.233.92
    clusterIPs:
    - 10.43.233.92
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 4111
      protocol: TCP
      targetPort: 3111
    selector:
      app: techtrends
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""